name: Build YDM

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Windows GNU target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Install dependencies
        run: |
          choco install mingw -y

      - name: Build Release
        run: cargo build --release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: YDM-Windows
          path: target/release/*.exe
